--- #YAML:1.0
name:               Net-Twitter
version:            2.00
abstract:           Perl interface to twitter.com
author:
    - Chris Thompson <cpan@cthompson.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON::Any:       1.19
    LWP::UserAgent:  0
    Test::More:      0
    URI::Escape:     0
no_index:
    directory:
        - t
        - inc
resources:
	license: http://dev.perl.org/licenses/
	homepage: http://search.cpan.org/dist/Net-Twitter/
	bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Twitter
	repository: git://github.com/ct/net-twitter.git
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
